


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."identificacion_types" AS ENUM (
    'CC',
    'CE',
    'PAS',
    'NIT',
    'PEP'
);


ALTER TYPE "public"."identificacion_types" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."bank" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "agreement_state" character varying,
    "swift" character varying,
    "address" character varying,
    "interest_rate" numeric
);


ALTER TABLE "public"."bank" OWNER TO "postgres";


ALTER TABLE "public"."bank" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."bank_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."constructora" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "nit" character varying,
    "phone" character varying,
    "email" character varying,
    "address" character varying,
    "country_id" bigint,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."constructora" OWNER TO "postgres";


ALTER TABLE "public"."constructora" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."construction_company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."countries" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "country_code" character varying NOT NULL,
    "country_phone_code" character varying
);


ALTER TABLE "public"."countries" OWNER TO "postgres";


ALTER TABLE "public"."countries" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."countries_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."currency" (
    "id" bigint NOT NULL,
    "currency_code" character varying NOT NULL,
    "description" character varying
);


ALTER TABLE "public"."currency" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."document" (
    "id" bigint NOT NULL,
    "document_type" character varying NOT NULL,
    "path" character varying
);


ALTER TABLE "public"."document" OWNER TO "postgres";


ALTER TABLE "public"."document" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."document_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."id_type" (
    "id" bigint NOT NULL,
    "type" character varying NOT NULL,
    "description" character varying
);


ALTER TABLE "public"."id_type" OWNER TO "postgres";


ALTER TABLE "public"."id_type" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."id_tipo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."leads" (
    "id" integer NOT NULL,
    "user_id" integer NOT NULL,
    "property_id" integer NOT NULL,
    "status" character varying(50) NOT NULL,
    "description" character varying(500),
    "source" character varying(100),
    "created_at" timestamp without time zone
);


ALTER TABLE "public"."leads" OWNER TO "postgres";


ALTER TABLE "public"."leads" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."leads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."logs" (
    "id" integer NOT NULL,
    "user_id" integer,
    "http_method" character varying(10) NOT NULL,
    "route" character varying(255) NOT NULL,
    "status_code" integer,
    "action_summary" character varying(255) NOT NULL,
    "created_at" timestamp without time zone NOT NULL
);


ALTER TABLE "public"."logs" OWNER TO "postgres";


ALTER TABLE "public"."logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."real_state" (
    "id" bigint NOT NULL,
    "value" numeric NOT NULL,
    "description" character varying,
    "address" character varying,
    "city" character varying,
    "constructora_id" bigint,
    "name" character varying,
    "country_id" bigint,
    "status" character varying NOT NULL,
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."real_state" OWNER TO "postgres";


ALTER TABLE "public"."real_state" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."property_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."realstate_phase" (
    "id" bigint NOT NULL,
    "state" character varying
);


ALTER TABLE "public"."realstate_phase" OWNER TO "postgres";


ALTER TABLE "public"."realstate_phase" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."realstate_phase_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sales" (
    "id" integer NOT NULL,
    "lead_id" integer NOT NULL,
    "agent_user_id" integer NOT NULL,
    "buyer_user_id" integer NOT NULL,
    "property_id" integer NOT NULL,
    "sale_price" numeric,
    "created_at" timestamp without time zone
);


ALTER TABLE "public"."sales" OWNER TO "postgres";


ALTER TABLE "public"."sales" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sales_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sold_property" (
    "id" bigint NOT NULL,
    "property_id" bigint NOT NULL,
    "user_id" bigint,
    "bank_id" bigint
);


ALTER TABLE "public"."sold_property" OWNER TO "postgres";


ALTER TABLE "public"."sold_property" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sold_properties_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "last_name" character varying,
    "street_address" character varying,
    "zip_code" character varying,
    "email" character varying,
    "residence_city" character varying,
    "country_id" bigint,
    "monthly_income" character varying,
    "job" character varying,
    "monthly_outcome" character varying,
    "desired_description" character varying,
    "identification_type" "public"."identificacion_types",
    "updated_at" timestamp without time zone,
    "created_at" timestamp without time zone,
    "identification" character varying,
    "user_id_role" integer,
    "date_of_birth" "date",
    "phone_number" character varying,
    "constructora_id" bigint
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE "public"."users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users_login" (
    "id" bigint NOT NULL,
    "user_id" bigint NOT NULL,
    "user_login" character varying NOT NULL,
    "created_at" timestamp with time zone,
    "user_password" character varying,
    "updated_at" timestamp with time zone,
    "active" boolean
);


ALTER TABLE "public"."users_login" OWNER TO "postgres";


ALTER TABLE "public"."users_login" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_list_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users_role" (
    "id" bigint NOT NULL,
    "role" character varying,
    "modules" "text"[] DEFAULT '{}'::"text"[]
);


ALTER TABLE "public"."users_role" OWNER TO "postgres";


ALTER TABLE "public"."users_role" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."users_role_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."bank"
    ADD CONSTRAINT "bank_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."constructora"
    ADD CONSTRAINT "construction_company_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_country_code_key" UNIQUE ("country_code");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."countries"
    ADD CONSTRAINT "countries_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."document"
    ADD CONSTRAINT "document_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."id_type"
    ADD CONSTRAINT "id_tipo_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."logs"
    ADD CONSTRAINT "logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."currency"
    ADD CONSTRAINT "moneda_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."real_state"
    ADD CONSTRAINT "property_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."real_state"
    ADD CONSTRAINT "real_state_address_key" UNIQUE ("address");



ALTER TABLE ONLY "public"."real_state"
    ADD CONSTRAINT "real_state_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."realstate_phase"
    ADD CONSTRAINT "realstate_phase_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sold_property"
    ADD CONSTRAINT "sold_properties_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users_login"
    ADD CONSTRAINT "users_list_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users_login"
    ADD CONSTRAINT "users_login_user_type_key" UNIQUE ("user_login");



ALTER TABLE ONLY "public"."users_role"
    ADD CONSTRAINT "users_role_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users_role"
    ADD CONSTRAINT "users_role_role_key" UNIQUE ("role");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "usuario_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."constructora"
    ADD CONSTRAINT "constructora_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "public"."real_state"("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."logs"
    ADD CONSTRAINT "logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."real_state"
    ADD CONSTRAINT "property_homebuilder_fkey" FOREIGN KEY ("constructora_id") REFERENCES "public"."constructora"("id");



ALTER TABLE ONLY "public"."real_state"
    ADD CONSTRAINT "real_state_constructora_id_fkey" FOREIGN KEY ("constructora_id") REFERENCES "public"."constructora"("id");



ALTER TABLE ONLY "public"."real_state"
    ADD CONSTRAINT "real_state_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id");



ALTER TABLE ONLY "public"."realstate_phase"
    ADD CONSTRAINT "realstate_phase_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."real_state"("id");



ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_agent_user_id_fkey" FOREIGN KEY ("agent_user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_buyer_user_id_fkey" FOREIGN KEY ("buyer_user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id");



ALTER TABLE ONLY "public"."sales"
    ADD CONSTRAINT "sales_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "public"."real_state"("id");



ALTER TABLE ONLY "public"."sold_property"
    ADD CONSTRAINT "sold_properties_bank_id_fkey" FOREIGN KEY ("bank_id") REFERENCES "public"."bank"("id");



ALTER TABLE ONLY "public"."sold_property"
    ADD CONSTRAINT "sold_properties_property_id_fkey" FOREIGN KEY ("property_id") REFERENCES "public"."real_state"("id");



ALTER TABLE ONLY "public"."sold_property"
    ADD CONSTRAINT "sold_properties_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_constructora_id_fkey" FOREIGN KEY ("constructora_id") REFERENCES "public"."constructora"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_country_id_fkey" FOREIGN KEY ("country_id") REFERENCES "public"."countries"("id");



ALTER TABLE ONLY "public"."users_login"
    ADD CONSTRAINT "users_list_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_user_id_role_fkey" FOREIGN KEY ("user_id_role") REFERENCES "public"."users_role"("id");



ALTER TABLE "public"."bank" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."constructora" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."countries" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."currency" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."document" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."id_type" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."real_state" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."realstate_phase" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sold_property" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users_login" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users_role" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";











































































































































































GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."bank" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."bank" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."bank" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."bank_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."bank_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."bank_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."constructora" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."constructora" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."constructora" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."construction_company_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."construction_company_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."construction_company_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."countries" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."countries" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."countries" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."countries_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."countries_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."countries_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."currency" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."currency" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."currency" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."document" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."document" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."document" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."document_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."document_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."document_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."id_type" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."id_type" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."id_type" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."id_tipo_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."id_tipo_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."id_tipo_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."leads" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."leads" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."leads" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."leads_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."leads_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."leads_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."logs" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."logs" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."logs" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."logs_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."logs_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."logs_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."real_state" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."real_state" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."real_state" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."property_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."property_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."property_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."realstate_phase" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."realstate_phase" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."realstate_phase" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."realstate_phase_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."realstate_phase_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."realstate_phase_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."sales" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."sales" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."sales" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."sales_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."sales_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."sales_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."sold_property" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."sold_property" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."sold_property" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."sold_properties_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."sold_properties_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."sold_properties_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."user_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."user_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."user_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users_login" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users_login" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users_login" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."users_list_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."users_list_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."users_list_id_seq" TO "service_role";



GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users_role" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users_role" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."users_role" TO "service_role";



GRANT UPDATE ON SEQUENCE "public"."users_role_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."users_role_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."users_role_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";































