-- Tablas de Leads, Ventas y Logs (CA3 y CA4) - Inverclick
--
-- COMO USAR ESTE ARCHIVO:
-- 1. Asegurate de tener ya creadas las tablas de Constructoras y
--    real_state (CA1/CA2) en tu Supabase local, porque leads y sales
--    tienen llaves foraneas (FK) que apuntan a real_state.
-- 2. Abre tu Supabase Studio local (http://127.0.0.1:54323).
-- 3. Ve a "SQL Editor" (menu de la izquierda).
-- 4. Pega TODO el contenido de este archivo y dale "Run".
-- 5. Listo: te deberian aparecer las tablas leads, logs y sales en el
--    esquema "inverclick" (Table Editor -> selector de esquema arriba).

CREATE TABLE IF NOT EXISTS inverclick.leads (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_id integer NOT NULL REFERENCES inverclick.users(id),
    property_id integer NOT NULL REFERENCES inverclick.real_state(id),
    status character varying(50) NOT NULL,
    description character varying(500),
    source character varying(100),
    created_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS inverclick.sales (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    lead_id integer NOT NULL REFERENCES inverclick.leads(id),
    agent_user_id integer NOT NULL REFERENCES inverclick.users(id),
    buyer_user_id integer NOT NULL REFERENCES inverclick.users(id),
    property_id integer NOT NULL REFERENCES inverclick.real_state(id),
    sale_price numeric,
    created_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS inverclick.logs (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_id integer REFERENCES inverclick.users(id) ON DELETE SET NULL,
    http_method character varying(10) NOT NULL,
    route character varying(255) NOT NULL,
    status_code integer,
    action_summary character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL
);
