CREATE TABLE IF NOT EXISTS public.leads (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id),
    property_id integer NOT NULL REFERENCES public.real_state(id),
    status character varying(50) NOT NULL,
    description character varying(500),
    source character varying(100),
    created_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.sales (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    lead_id integer NOT NULL REFERENCES public.leads(id),
    agent_user_id integer NOT NULL REFERENCES public.users(id),
    buyer_user_id integer NOT NULL REFERENCES public.users(id),
    property_id integer NOT NULL REFERENCES public.real_state(id),
    sale_price numeric,
    created_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS public.logs (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_id integer REFERENCES public.users(id) ON DELETE SET NULL,
    http_method character varying(10) NOT NULL,
    route character varying(255) NOT NULL,
    status_code integer,
    action_summary character varying(255) NOT NULL,
    created_at timestamp without time zone NOT NULL
);

